import React from 'react';
import { useSimulation } from '../context/SimulationContext';
import { 
  ResponsiveContainer, 
  AreaChart, 
  Area, 
  LineChart, 
  Line, 
  XAxis, 
  YAxis, 
  Tooltip, 
  CartesianGrid 
} from 'recharts';
import { 
  Zap, 
  ShieldAlert, 
  Activity, 
  Compass,
  ArrowUpRight,
  TrendingDown,
  Terminal,
  Settings
} from 'lucide-react';

const Dashboard = () => {
  const {
    themeMode,
    presets,
    loadPreset,
    preset,
    notifications,
    history,
    gmi,
    stability,
    negMassDensity,
    power,
    levitationStatus,
    playClick
  } = useSimulation();

  // Color variables based on theme
  const getThemeColors = () => {
    switch (themeMode) {
      case 'academic':
        return {
          cardBg: 'bg-slate-900/40 border-slate-800',
          textActive: 'text-emerald-400',
          chartColor1: '#10b981', // emerald
          chartColor2: '#0d9488', // teal
          accentBorder: 'border-slate-800',
          badgeBg: 'bg-emerald-950/20 text-emerald-400 border-emerald-800/40'
        };
      case 'classified':
        return {
          cardBg: 'bg-cyber-obsidian/80 border-cyber-amber/20',
          textActive: 'text-cyber-amber',
          chartColor1: '#ffaa00', // amber
          chartColor2: '#cc8800', // dark amber
          accentBorder: 'border-cyber-amber/30',
          badgeBg: 'bg-cyber-amber/5 text-cyber-amber border-cyber-amber/30'
        };
      case 'sci-fi':
      default:
        return {
          cardBg: 'bg-cyber-dark/40 border-cyber-blue/15',
          textActive: 'text-cyber-blue',
          chartColor1: '#00f0ff', // cyber-blue
          chartColor2: '#00ff87', // cyber-green
          accentBorder: 'border-cyber-blue/30',
          badgeBg: 'bg-cyber-blue/5 text-cyber-blue border-cyber-blue/25'
        };
    }
  };

  const colors = getThemeColors();

  // Metrics details mapping
  const metricsData = [
    {
      name: "Gravity Manipulation Index (GMI)",
      value: `${gmi.toFixed(2)} G₀`,
      sub: "Field Warp factor",
      icon: Compass,
      status: gmi > 1.3 ? "ACTIVE" : "STANDBY",
      statusColor: gmi > 1.3 ? "text-cyber-green" : "text-gray-500",
      description: "Measure of space-time deflection force relative to standard Earth gravity."
    },
    {
      name: "Quantum Field Stability",
      value: `${stability}%`,
      sub: "Resonance Coherence",
      icon: Activity,
      status: stability > 70 ? "STABLE" : stability > 45 ? "WARNING" : "CRITICAL",
      statusColor: stability > 70 ? "text-cyber-green" : stability > 45 ? "text-cyber-amber" : "text-cyber-red animate-pulse",
      description: "Indicates how well the electromagnetic oscillator frequency balances local gravitational vectors."
    },
    {
      name: "Negative Mass Density",
      value: `${negMassDensity.toFixed(4)} g/cm³`,
      sub: "Casimir Cavity Pressure",
      icon: ShieldAlert,
      status: negMassDensity < 0 ? "ATTENUATED" : "INACTIVE",
      statusColor: negMassDensity < 0 ? "text-cyber-blue" : "text-gray-500",
      description: "Effective mass density inside Casimir cavities generated by high negative energy injection."
    },
    {
      name: "Power Consumption",
      value: `${power} GW`,
      sub: "Propulsion Grid Draw",
      icon: Zap,
      status: power > 800 ? "PEAK LOAD" : "NOMINAL",
      statusColor: power > 800 ? "text-cyber-red" : "text-cyber-green",
      description: "Electrical energy supply required to sustain the antimass gravity vector field."
    }
  ];

  return (
    <div className="p-6 space-y-6 overflow-y-auto h-full max-h-screen select-none">
      
      {/* Upper Status Banner */}
      <div className={`cyber-panel border p-4 flex flex-col md:flex-row justify-between items-start md:items-center gap-4 ${colors.cardBg} ${themeMode === 'classified' ? 'cyber-panel-amber' : themeMode === 'academic' ? '' : 'cyber-panel-blue'}`}>
        <div className="cyber-corners text-inherit absolute inset-0 pointer-events-none" />
        <div className="space-y-1">
          <h1 className="font-orbitron font-extrabold text-lg tracking-wider text-white flex items-center gap-2">
            SYSTEM CORE STATUS: 
            <span className={`px-2 py-0.5 rounded text-xs border ${
              levitationStatus === 'STABLE' 
                ? 'bg-cyber-green/10 text-cyber-green border-cyber-green/30' 
                : levitationStatus === 'UNSTABLE'
                ? 'bg-cyber-amber/10 text-cyber-amber border-cyber-amber/30 animate-pulse'
                : 'bg-cyber-red/10 text-cyber-red border-cyber-red/30'
            }`}>
              {levitationStatus} LEVITATION
            </span>
          </h1>
          <p className="text-xs text-gray-500">Real-time simulation environment synchronized via Quantum Telemetry link.</p>
        </div>
        
        {/* Preset Selectors */}
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-[10px] text-gray-500 font-bold uppercase tracking-wider">Presets:</span>
          {Object.keys(presets).map((key) => (
            <button
              key={key}
              onClick={() => loadPreset(key)}
              className={`px-3 py-1.5 text-[10px] font-orbitron font-bold tracking-wider transition-all duration-150 btn-cyber ${
                preset === key
                  ? themeMode === 'classified'
                    ? 'bg-cyber-amber text-black'
                    : themeMode === 'academic'
                    ? 'bg-emerald-600 text-white'
                    : 'bg-cyber-blue text-black'
                  : 'bg-gray-950 text-gray-400 hover:text-white border border-gray-800'
              }`}
            >
              {key.toUpperCase().replace('_', ' ')}
            </button>
          ))}
        </div>
      </div>

      {/* Grid of four main metrics cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {metricsData.map((metric, idx) => {
          const Icon = metric.icon;
          return (
            <div 
              key={idx} 
              className={`cyber-panel border p-4 flex flex-col justify-between ${colors.cardBg} ${themeMode === 'classified' ? 'cyber-panel-amber' : ''} h-36 relative`}
            >
              <div className="sweep-line" />
              <div className="flex justify-between items-start">
                <div className="space-y-1">
                  <span className="text-[10px] text-gray-500 uppercase tracking-wider font-semibold block">{metric.name}</span>
                  <span className="text-2xl font-orbitron font-black tracking-tight text-white block">
                    {metric.value}
                  </span>
                </div>
                <div className={`p-2 rounded border border-gray-800 bg-gray-950/80`}>
                  <Icon className={`w-4 h-4 ${colors.textActive}`} />
                </div>
              </div>
              <div className="flex justify-between items-center text-[10px] border-t border-gray-900 pt-2 mt-2">
                <span className="text-gray-500 uppercase tracking-wider">{metric.sub}</span>
                <span className={`font-bold tracking-widest ${metric.statusColor}`}>{metric.status}</span>
              </div>
            </div>
          );
        })}
      </div>

      {/* Center Section: Telemetry Charts + Terminal logs */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Real-time charts */}
        <div className={`cyber-panel border p-5 lg:col-span-2 space-y-4 ${colors.cardBg} ${themeMode === 'classified' ? 'cyber-panel-amber' : ''}`}>
          <div className="flex justify-between items-center border-b border-gray-900 pb-2">
            <h2 className="font-orbitron text-xs font-bold tracking-widest uppercase text-white flex items-center gap-2">
              <Activity className="w-4 h-4 text-cyber-blue" />
              Wave Coherence & anomaly Telemetry
            </h2>
            <span className="text-[9px] text-gray-500 animate-pulse">● FEED ACTIVE</span>
          </div>

          <div className="h-64 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={history} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <defs>
                  <linearGradient id="colorGmi" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor={colors.chartColor1} stopOpacity={0.3}/>
                    <stop offset="95%" stopColor={colors.chartColor1} stopOpacity={0}/>
                  </linearGradient>
                  <linearGradient id="colorStability" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor={colors.chartColor2} stopOpacity={0.2}/>
                    <stop offset="95%" stopColor={colors.chartColor2} stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255, 255, 255, 0.03)" />
                <XAxis dataKey="time" tick={{ fill: '#4b5563', fontSize: 9 }} />
                <YAxis tick={{ fill: '#4b5563', fontSize: 9 }} />
                <Tooltip 
                  contentStyle={{ 
                    backgroundColor: '#020306', 
                    borderColor: 'rgba(0, 240, 255, 0.2)', 
                    fontSize: '10px',
                    fontFamily: 'JetBrains Mono',
                    color: '#fff' 
                  }} 
                />
                <Area 
                  type="monotone" 
                  dataKey="stability" 
                  name="Field Stability (%)"
                  stroke={colors.chartColor2} 
                  fillOpacity={1} 
                  fill="url(#colorStability)" 
                />
                <Area 
                  type="monotone" 
                  dataKey="anomaly" 
                  name="Anomaly Spike"
                  stroke="#ff0055" 
                  fillOpacity={0.1}
                  fill="rgba(255, 0, 85, 0.05)"
                />
                <Line 
                  type="monotone" 
                  dataKey="gmi" 
                  stroke={colors.chartColor1} 
                  strokeWidth={2}
                  name="GMI Value"
                  dot={false}
                />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Live system logs */}
        <div className={`cyber-panel border p-5 flex flex-col justify-between ${colors.cardBg} ${themeMode === 'classified' ? 'cyber-panel-amber' : ''}`}>
          <div className="flex justify-between items-center border-b border-gray-900 pb-2 mb-3">
            <h2 className="font-orbitron text-xs font-bold tracking-widest uppercase text-white flex items-center gap-2">
              <Terminal className="w-4 h-4 text-cyber-blue" />
              Quantum propulsion log
            </h2>
            <button 
              onClick={() => playClick()} 
              className="text-[9px] hover:underline text-gray-500 uppercase tracking-widest"
            >
              Clear
            </button>
          </div>

          <div className="flex-grow overflow-y-auto space-y-2 max-h-56 scrollbar-thin text-[10px] font-mono pr-2">
            {notifications.length === 0 ? (
              <div className="text-gray-600 italic">No quantum anomalies detected. Log clean.</div>
            ) : (
              notifications.map((log) => (
                <div key={log.id} className="flex gap-2 items-start border-l border-gray-800 pl-2 leading-relaxed">
                  <span className="text-cyber-blue/60 font-semibold flex-shrink-0 select-none">[{log.time}]</span>
                  <span className="text-gray-300 select-all">{log.text}</span>
                </div>
              ))
            )}
          </div>

          <div className="mt-4 pt-3 border-t border-gray-900 flex items-center justify-between text-[9px] text-gray-500 font-bold">
            <span>DIAGNOSTIC CHANNEL: #Q-42</span>
            <span>CORE TEMP: 34.2 K</span>
          </div>
        </div>
      </div>

      {/* Preset scientific descriptions */}
      <div className={`cyber-panel border p-4 ${colors.cardBg} ${themeMode === 'classified' ? 'cyber-panel-amber' : ''}`}>
        <h3 className="font-orbitron text-[11px] font-bold tracking-widest uppercase text-white mb-2">
          Theoretical Foundation Preset Details
        </h3>
        <p className="text-xs text-gray-400 leading-relaxed font-sans">
          Currently analyzing <strong className={colors.textActive}>{presets[preset]?.name}</strong>: {presets[preset]?.description} 
          This physics environment is derived from popular science documentaries, historical investigations, and peer-reviewed relativity metrics, modeling gravitational fields as dynamic electromagnetic configurations.
        </p>
      </div>

    </div>
  );
};

export default Dashboard;
